### ISSUE TITLE
Error on Macbook Air M1: no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by SRICKKY** [Genc/spring-boot-boilerplate#20]
### no matching manifest for linux/arm64/v8 in the manifest list entries
<img width="1680" alt="Screenshot 2024-03-03 at 7 26 13 PM" src="https://github.com/Genc/spring-boot-boilerplate/assets/10415544/8f058e30-8011-4165-b515-a8318f784dec">

**Comment by Genc** [comment]
@SRICKKY Hey man, I've seen this problem happen with M1 users, have you tried [this](https://stackoverflow.com/a/67361161)?

Maybe you could just define your own compose file like this?

```
  db:
    platform: linux/x86_64
    container_name: db
```

Can you let me know when you've tried it?
